### ISSUE TITLE
ATMS Obs Validation

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/JEDI-T2O#42]
**This issue will be used to track progress on the development and validation of radiances in UFO for GDAS in four stages:**

**1. Validation with GeoVaLs from GSI:**
 - [x] **HofX**

- The [**initial validation showed a large HofX difference**](https://github.com/NOAA-EMC/JEDI-T2O/issues/42#issuecomment-1381084705) (no QC) between GSI and JEDI  for surface sensitive channels over snow area.

- CRTM has known issues with ATMS surface snow and ice emissivity models.  CRTM has a float-point error when the input observations (surface channels) contain missing values.  The issues and short-term fixes were documented in the following GitHub issues and PRs:
`Snow-related`
Issue: [JCSDA-internal/ufo-old#1100](https://github.com/JCSDA-internal/ufo-old/issues/1100) 
PR: [DA-internal/crtm-old#74](https://github.com/JCSDA-internal/crtm-old/pull/74) --- snow fix in NESDIS_ATMS_SnowEM_Module.f90
`Ice-related`
Issue: [JCSDA-internal/ufo#621](https://github.com/JCSDA-internal/ufo/issues/621)
PR: [JCSDA-internal/crtm#371](https://github.com/JCSDA-internal/crtm/pull/371)  --- sea ice fix in NESDIS_ATMS_SeaICE_Module.f90

- Both GSI and GDASApp for JEDI use CRTM-2.3.0.  However, GSI CRTM does not have both ice/snow emissivity fix, and the GDASApp for JEDI does not have the ice emissivity fix.  To have a fair comparison, CRTM in GSI and GDASApp has been updated with the fixes.   The updated input obs and geoval files are available in the following location on ORION.

```    
          Date: 2021080100
          Resolution: C768
          GeoDir=/work2/noaa/da/eliu/ufoeval/GSIobserver/2021080100/ioda/geovals/
          ObsDir=/work2/noaa/da/eliu/ufoeval/GSIobserver/2021080100/ioda/obs/
          BCDir=/work2/noaa/da/cmartin/UFO_eval/data/gsi_geovals_l127/nofgat_aug2021/20221027/bc/
          FixDir=/work2/noaa/da/cmartin/GDASApp/fix/
```

- With the updated CRTM, the HofX comparison (no QC) between GSI and UFO shows **100% agreement**
    - [x] [**ATMS NPP**](https://github.com/NOAA-EMC/JEDI-T2O/issues/42#issuecomment-1381090898)
    - [x] [**ATMS N20**](https://github.com/NOAA-EMC/JEDI-T2O/issues/42#issuecomment-1381256337)

- [x] **Update/improve QC filters** (GSI QC steps in GSI setuprad.f90 and qcmod.f90 (qc_atms subroutine)

![ATMS-QC-Flowchart pptx](https://user-images.githubusercontent.com/36091766/212228755-b26fe0d8-137b-4506-92b4-72f02552180b.png)

   - [x] The @ObsError is set to missing in the input obs file
   - [x] Code change is required for ObsErrorFactorSituDependMW to avoid getting the original obs error from the input obs file
   - [x] Code change is required for ObsErrorFactorSituDependMW to fix a big - there should be no inflation based on the scattering index for ATMS.  
   - [x] **YAML update**
           - Improve the use of generic filters and obs functions in the YAML
           - Add filters to output diagnostic variables in YAML
           - Remove the need to repeatedly re-compute the same obs functions used in various filters 
- [x] **QC count  and obs error checks using-GSI produced GeoVaLs**
   - [ ] Validation Results: [**ObsError** ](https://github.com/NOAA-EMC/JEDI-T2O/issues/42#issuecomment-1382432879)and [**HofX**](https://github.com/NOAA-EMC/JEDI-T2O/issues/42#issuecomment-1382433469) 
       - [x] atms_npp - 100% replication except for [**one observation for channel 7 in the hydrometer check**](https://github.com/NOAA-EMC/JEDI-T2O/issues/42#issuecomment-1382598083)
       - [x] atms_n20 - 100% replication except for [**two observations for channel 7 in the hydrometer check**](https://github.com/NOAA-EMC/JEDI-T2O/issues/42#issuecomment-1382598083)
Note: The differences likely come from numerical round-off errors.

**2. UFO development:**
- [ ] Separate `HydrometeorCheckATMS` into three separate checks for clarity --- work in progress 
- [ ] Modify existing Gaussian thinning filter to reproduce GSI result   --- work in progress
- [ ] Check with JEDI team about keeping the thinned data in the obs space
- [ ] Add thinning filter and a few more QC steps (from GSI read_bufrtovs.f90 routine) in YAML
- [ ] Validation with GSI result

**3. IODA-converter development:**
- [ ] Prepare ATMS YAML for bufr converter with channel remapping capability
- [ ] Work with Cory to add the capability of converting ATMS bufr to IODA in GDASApp workflow

**4. HofX computation in FV3-JEDI with GDASApp workflow:**
- [ ] Test workflow (plumbing)
- [ ] Check statistics
- [ ] Summarize and explain the differences between GSI and UFO

**Comment by ADCollard** [comment]
This also references #39

**Comment by emilyhcliu** [comment]
**ATMS NPP (No QC)**
**Surface-sensitive Channels**
channel-2 | channel-16
--- | ---
![](https://user-images.githubusercontent.com/36091766/212198318-832b8220-fc63-4eab-a59f-6fc5b1a1360a.png)|![](https://user-images.githubusercontent.com/36091766/212198345-c7ef8c87-b046-4e85-9117-e827268de7f9.png)

channel-2 | channel-16
--- | ---
![](https://user-images.githubusercontent.com/36091766/212198736-4c5c33c7-0445-426c-8b5b-ae8b3fda5487.png)|![](https://user-images.githubusercontent.com/36091766/212198754-d43339a8-c2d6-4275-8eeb-c9042eb9cf7c.png)

**Stratospheric Temperature Channels**
channel-11 | channel-15
--- | ---
![](https://user-images.githubusercontent.com/36091766/212198465-9818b0a9-1ea1-47e7-bbf2-063208aba4f6.png)| ![](https://user-images.githubusercontent.com/36091766/212198473-170a47a0-d860-484f-9dc3-4aac39be1b55.png)

channel-11 | channel-15
--- | ---
![](https://user-images.githubusercontent.com/36091766/212198813-10d2906c-695a-44d4-be12-7b0dbe6f6232.png)|![](https://user-images.githubusercontent.com/36091766/212198837-4b9c9afe-3c9f-4769-b5b9-8375fcbf572e.png)

**Moisture Channels (Tropospheric)**
channel-17 | channel-22
--- | ---
![](https://user-images.githubusercontent.com/36091766/212198581-ed6a26b7-fd18-4de7-9f32-aa330aed3bc1.png)|![](https://user-images.githubusercontent.com/36091766/212198600-e326b382-c061-48e7-801e-7b6aa24aafe3.png)

channel-17 | channel-22
--- | ---
![](https://user-images.githubusercontent.com/36091766/212199227-a394efc1-469e-4358-bd1d-c63a70462070.png)|![](https://user-images.githubusercontent.com/36091766/212199251-57e6a8f7-c840-4ccc-9d30-d1e77f114662.png)

Note: ATMS N20 also showed the similar large difference between GSI and UFO over snow area.

**Comment by emilyhcliu** [comment]
**ATMS NPP (No QC)**
channel-1 | channel-2
--- |---
![](https://user-images.githubusercontent.com/36091766/212199645-846934c6-f141-4cde-aeff-8254c9004b64.png)|![](https://user-images.githubusercontent.com/36091766/212199649-49a9d616-39cd-48ea-8a17-b0e4177a59b7.png)

channel-3|channel-4
--- | --- 
![](https://user-images.githubusercontent.com/36091766/212199650-da5d2888-5732-4d92-8e22-ce898823a497.png)|![](https://user-images.githubusercontent.com/36091766/212199651-29d25e93-ea0b-47bd-9e0e-d885ad2ce3cb.png)

channel-5 | channel-6|
|--- |---
![](https://user-images.githubusercontent.com/36091766/212199652-2e070ee1-1832-4caa-adcf-9993a259305e.png)|![](https://user-images.githubusercontent.com/36091766/212199654-1530a5b5-030d-4174-9716-535aa454974c.png)

channel-7|channel-8
--- | --- 
![](https://user-images.githubusercontent.com/36091766/212199655-ec9f50aa-aac2-4204-9b8e-b66cfd612e57.png)|![](https://user-images.githubusercontent.com/36091766/212199657-f6593c20-932a-4ce6-a81d-08e66c113070.png)

channel-9 | channel-10
--- |---
![](https://user-images.githubusercontent.com/36091766/212199659-a4498519-23b6-44f7-b3da-d88812fe1f17.png)|![](https://user-images.githubusercontent.com/36091766/212199661-28973a6f-941d-4c97-83fb-4cdfd81a91fb.png)

channel-11|channel-12
--- | --- 
![](https://user-images.githubusercontent.com/36091766/212199662-d49c5d06-0375-45b2-ab8b-158805ced314.png)|![](https://user-images.githubusercontent.com/36091766/212199663-fbc84f3c-021d-40ad-8023-18c7211759e9.png)

channel-13 | channel-14
--- | --- 
![](https://user-images.githubusercontent.com/36091766/212199664-1626f10b-eacf-4095-90d2-4aa1cadec007.png)|![](https://user-images.githubusercontent.com/36091766/212199665-ef26cf10-762c-4a51-94ce-db92a10b9290.png)

channel-15|channel-16
--- |---
![](https://user-images.githubusercontent.com/36091766/212199669-a2ff8807-8193-4e39-a0ff-bd01159ddd43.png)|![](https://user-images.githubusercontent.com/36091766/212199671-07a0e8d7-5197-444a-97cc-071e630ebd24.png)

channel-1 7| channel-18
--- |---
![](https://user-images.githubusercontent.com/36091766/212199673-2e207eed-ddeb-43a8-b64c-8a9d39cfa999.png)|![](https://user-images.githubusercontent.com/36091766/212199675-ea0b6679-c39b-4ba2-ad44-3c57095d9bd8.png)

|channel-19|channel-20
--- | --- |
![](https://user-images.githubusercontent.com/36091766/212199677-02ebbd3e-a84b-4405-88ba-341e0e423ea9.png)|![](https://user-images.githubusercontent.com/36091766/212199678-d3c6c019-93ac-4485-9ae2-ae90a7bab224.png)

channel-21 | channel-22
--- |---
![](https://user-images.githubusercontent.com/36091766/212201899-d6d208c2-4e32-4ec8-b20a-498dcc7ddcb1.png)|![](https://user-images.githubusercontent.com/36091766/212201900-0f13de8d-9e7e-4167-9451-56f2fb306fc0.png)

**Comment by emilyhcliu** [comment]
**ATMS N20 (No QC)**
channel-1 | channel-2
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature1](https://user-images.githubusercontent.com/36091766/212227324-87ccc720-92f1-46cb-8cf4-d1e9cd4a2e26.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature2](https://user-images.githubusercontent.com/36091766/212227326-6b78fa34-6587-4217-ade4-6c9677b2bb48.png)

channel-3|channel-4
--- | --- 
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature3](https://user-images.githubusercontent.com/36091766/212227370-07160543-ec8f-48c0-8af8-5cdc785d93e6.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature4](https://user-images.githubusercontent.com/36091766/212227371-19583a33-df9d-427a-9dae-0671621b6c34.png)

channel-5 | channel-6|
|--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature5](https://user-images.githubusercontent.com/36091766/212227397-ad6b6a88-1923-4e21-a9fc-d15934b96247.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature6](https://user-images.githubusercontent.com/36091766/212227398-50360abb-4146-4102-b19a-fb1efd1616bf.png)

channel-7|channel-8
--- | --- 
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature7](https://user-images.githubusercontent.com/36091766/212227427-f4e7b8bc-9115-4db2-8ca7-ba15b5f99c87.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature8](https://user-images.githubusercontent.com/36091766/212227429-b47324f6-579e-4760-bfd1-8a47589727ef.png)

channel-9 | channel-10
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature9](https://user-images.githubusercontent.com/36091766/212227446-9571bdcc-33c1-468d-9b58-7aec97d04c01.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature10](https://user-images.githubusercontent.com/36091766/212227447-e6001476-e9b3-4744-b404-cba9a9045eb9.png)

channel-11|channel-12
--- | --- 
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature11](https://user-images.githubusercontent.com/36091766/212227465-19377de3-7ac4-47dd-9ccf-706faff3893e.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature12](https://user-images.githubusercontent.com/36091766/212227467-f921f825-f42f-4ce9-b1d5-045f8dd79a93.png)

channel-13 | channel-14
--- | ---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature13](https://user-images.githubusercontent.com/36091766/212227511-0b484c2a-c214-47e3-952d-ee05e1ad9aeb.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature14](https://user-images.githubusercontent.com/36091766/212227512-67c2a746-b2b3-4682-bfee-f45e1bc68bc2.png)

channel-15|channel-16
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature15](https://user-images.githubusercontent.com/36091766/212227556-36644703-9ca3-4f25-9259-83f18495a616.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature16](https://user-images.githubusercontent.com/36091766/212227558-5506a551-ba6f-4ff9-92b1-459e0da09139.png)

channel-1 7| channel-18
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature17](https://user-images.githubusercontent.com/36091766/212227591-2ad12138-d49a-47a6-83fa-126833c6481c.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature18](https://user-images.githubusercontent.com/36091766/212227592-a437e61f-d2ad-488b-b827-a2f148ca7093.png)

|channel-19|channel-20
--- | --- |
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature19](https://user-images.githubusercontent.com/36091766/212227619-7df58663-7a28-448c-998c-f541d6b1f524.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature20](https://user-images.githubusercontent.com/36091766/212227620-d1b95992-53a8-452e-ba7e-e14aea44e734.png)

channel-21 | channel-22
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature21](https://user-images.githubusercontent.com/36091766/212227635-894bb530-1010-475b-b29c-7a7148d2db82.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature22](https://user-images.githubusercontent.com/36091766/212227636-c9a57792-1e67-4f7f-952a-a844bca57e35.png)

**Comment by emilyhcliu** [comment]
### Initial (Original) / Final Observation Error Comparison: GSI vs. JEDI UFO

**Result of QC filtering check  (using ATMS N20 as an example)**
The following figures show the GSI final observation error on the left and UFO on the right
The data count passed QC is listed above the color bar

**Original Observation Error**
**Channel-2**
GSI | UFO |
--- | ---
![gsi_initialobserr_atms_n20_channel2](https://user-images.githubusercontent.com/36091766/212438702-e9c369a4-6c62-4e43-9d73-535763a5e10d.png)|![ufo_initialobserr_atms_n20_channel2](https://user-images.githubusercontent.com/36091766/212438707-ee25f99c-c4e8-476a-815b-a264ed8a9f47.png)

**Observation Error after a series of data filtering and error inflation process:**
**Channel-2**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel2](https://user-images.githubusercontent.com/36091766/212438645-a1b409ee-ed51-48a8-8b56-5357debdde4e.png)|![ufo_atms_n20_channel2](https://user-images.githubusercontent.com/36091766/212438649-3e91f050-c9d0-45b2-a5c1-197c28afa794.png)

**Channel-1**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel1](https://user-images.githubusercontent.com/36091766/212438742-3ea16c53-dfe9-44c4-b020-8285c4607ae7.png)|![ufo_atms_n20_channel1](https://user-images.githubusercontent.com/36091766/212438745-408a3b33-7aab-43b5-9ad7-4aec740b2d8a.png)

**Channel-3**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel3](https://user-images.githubusercontent.com/36091766/212438754-f54b9fd5-3fa0-4e9f-99c7-40789ad816a6.png)|![ufo_atms_n20_channel3](https://user-images.githubusercontent.com/36091766/212438762-42061cc8-6f6d-4053-be89-c7c4d76f0fa7.png)

**Channel-4**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel4](https://user-images.githubusercontent.com/36091766/212438771-c4ecad4d-4b52-4177-a514-28be850d5eb8.png)|![ufo_atms_n20_channel4](https://user-images.githubusercontent.com/36091766/212438777-037e89ca-1229-4dc4-b97d-28533d94303e.png)

**Channel-5**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel5](https://user-images.githubusercontent.com/36091766/212438785-0fd62f96-e873-4027-b496-d3e495af7e4c.png)|![ufo_atms_n20_channel5](https://user-images.githubusercontent.com/36091766/212438790-0f1fa50f-68d2-471c-b753-d227f76ac6e7.png)

**Channel-6**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel6](https://user-images.githubusercontent.com/36091766/212438798-7e4d14ed-cfa8-484b-96de-540ee73156bc.png)|![ufo_atms_n20_channel6](https://user-images.githubusercontent.com/36091766/212438804-8262df52-0777-4312-95fb-652880ed3c00.png)

**Channel-7**  --- Difference in two observations 
GSI | UFO |
--- | ---
![gsi_atms_n20_channel7](https://user-images.githubusercontent.com/36091766/212438815-537a20e7-2a92-4d96-bb07-85b62b014318.png)|![ufo_atms_n20_channel7](https://user-images.githubusercontent.com/36091766/212438826-9e374a83-136b-4751-a268-92391948c0a3.png)



**Channel-8**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel8](https://user-images.githubusercontent.com/36091766/212438836-91d7f8c3-b965-4283-b55c-99bb4009b6c0.png)|![ufo_atms_n20_channel8](https://user-images.githubusercontent.com/36091766/212438842-e9152190-18d2-41b1-bb68-701dfeb94d2e.png)

**Channel-9**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel9](https://user-images.githubusercontent.com/36091766/212438851-f63a0cd6-5725-40d4-81e8-8e8b9ade174d.png)|![ufo_atms_n20_channel9](https://user-images.githubusercontent.com/36091766/212438862-63cd0345-d23c-4f82-ab4d-b977ca9dfce6.png)

**Channel-10**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel10](https://user-images.githubusercontent.com/36091766/212438871-a440a38b-7e7b-43d3-a276-8cdabe3475d1.png)|![ufo_atms_n20_channel10](https://user-images.githubusercontent.com/36091766/212438878-69914232-f226-435a-baf3-500ba3584655.png)

**Channel-11**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel11](https://user-images.githubusercontent.com/36091766/212438887-925b5032-4bf2-477d-bd27-83939858c78e.png)|![ufo_atms_n20_channel11](https://user-images.githubusercontent.com/36091766/212438892-60f91f97-c25e-4922-95a5-a58801a05477.png)

**Channel-12**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel12](https://user-images.githubusercontent.com/36091766/212438899-573a38a9-e89a-4984-97ab-669690a2fc2b.png)|![ufo_atms_n20_channel12](https://user-images.githubusercontent.com/36091766/212438908-a8ab4b0e-629b-492f-ba18-0e79a50efbe9.png)

**Channel-13**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel13](https://user-images.githubusercontent.com/36091766/212438937-42d97e5f-ac6d-4c12-9a6b-cc2d7f6ae065.png)|![ufo_atms_n20_channel13](https://user-images.githubusercontent.com/36091766/212438941-615dff3d-0cf2-4969-8ca6-cbace79a109d.png)

**Channel-14**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel14](https://user-images.githubusercontent.com/36091766/212438962-fddfc360-f9fe-46a0-90df-3f67940b19b3.png)|![ufo_atms_n20_channel14](https://user-images.githubusercontent.com/36091766/212438967-e85c51ac-556b-4846-9852-e58216ee54bd.png)

**Channel-15**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel15](https://user-images.githubusercontent.com/36091766/212438996-758311d8-dd9d-4d5f-9839-db2a5715a372.png)|![ufo_atms_n20_channel15](https://user-images.githubusercontent.com/36091766/214122217-f676f70f-cdc3-464c-ab70-443b7ac9b1ec.png)

**Channel-16**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel16](https://user-images.githubusercontent.com/36091766/212439016-414cfb60-b5f2-4990-987a-3d27fd8c0ddf.png)|![ufo_atms_n20_channel16](https://user-images.githubusercontent.com/36091766/212439023-d0f19382-ed8a-4487-b16e-4e4a7cd6f1ab.png)

**Channel-17**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel17](https://user-images.githubusercontent.com/36091766/212439034-4718f832-8292-4ff4-9630-c26fa6035971.png)|![ufo_atms_n20_channel17](https://user-images.githubusercontent.com/36091766/212439040-bbdb41a1-0ed2-417d-a0f0-7c7f4c532d54.png)

**Channel-18**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel18](https://user-images.githubusercontent.com/36091766/212439073-88faffa2-dad2-45c2-b641-c8a16ed2e6d1.png)|![ufo_atms_n20_channel18](https://user-images.githubusercontent.com/36091766/212439082-d095ed33-991b-4efa-a942-37151543577c.png)

**Channel-19**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel19](https://user-images.githubusercontent.com/36091766/212439102-ed395caf-1daf-46a3-a330-81a74c6031fa.png)|![ufo_atms_n20_channel19](https://user-images.githubusercontent.com/36091766/212439114-f7398269-e801-4680-a7af-04daed244e94.png)

**Channel-20**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel20](https://user-images.githubusercontent.com/36091766/212439132-80a6fde2-8ac3-4505-84bb-d5e790caa7b9.png)|![ufo_atms_n20_channel20](https://user-images.githubusercontent.com/36091766/212439142-164a2e35-3876-463d-b803-f5d982b8b668.png)

**Channel-21**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel21](https://user-images.githubusercontent.com/36091766/212439150-f5a55ee2-d6e8-4561-95d7-27aa8bf29f15.png)|![ufo_atms_n20_channel21](https://user-images.githubusercontent.com/36091766/212439154-cafac133-b2f6-4de6-83f4-047d12605b30.png)

**Channel-22**
GSI | UFO |
--- | ---
![gsi_atms_n20_channel22](https://user-images.githubusercontent.com/36091766/212439173-513026f5-b473-48c5-a597-ab7c40c5fdf6.png)|![ufo_atms_n20_channel22](https://user-images.githubusercontent.com/36091766/212439178-8132a5ec-b369-4817-8435-d7af07ec6362.png)

**Comment by emilyhcliu** [comment]
### **HofX  Comparison between GSI vs. JEDI UFO:  No QC (Black) and QC (Red)**
**AMSU-N20**

channel-1 | channel-2
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature1](https://user-images.githubusercontent.com/36091766/212429442-8a9d99c1-9b60-4734-a0eb-18a969284085.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature2](https://user-images.githubusercontent.com/36091766/212429443-5987e979-fa90-468c-90da-9df17ec6d08b.png)

channel-3|channel-4
--- | --- 
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature3](https://user-images.githubusercontent.com/36091766/212429469-41a0156e-3bbe-4f28-94c6-330bf25a4275.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature4](https://user-images.githubusercontent.com/36091766/212429471-d9f3cd3b-e4d3-404d-8ecb-d64ab4191526.png)

channel-5 | channel-6|
|--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature5](https://user-images.githubusercontent.com/36091766/212429490-818c6d3a-921d-4ba3-b6d2-54f09cb3f6dd.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature6](https://user-images.githubusercontent.com/36091766/212429491-b5432bb6-070a-41ec-a96b-6dfb4597e796.png)

channel-7|channel-8
--- | --- 
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature7](https://user-images.githubusercontent.com/36091766/212429517-0b671ca0-d942-43b2-9230-342053b6ec22.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature8](https://user-images.githubusercontent.com/36091766/212429522-c7d13604-ad6d-4484-8807-fa3a53a6b7c5.png)

channel-9 | channel-10
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature9](https://user-images.githubusercontent.com/36091766/212429543-0271c60c-35bd-4a57-8d27-bb4c733a12be.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature10](https://user-images.githubusercontent.com/36091766/212429544-99dce161-7483-4d8f-a762-9aee32500a23.png)

channel-11|channel-12
--- | --- 
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature11](https://user-images.githubusercontent.com/36091766/212429557-127207c0-7a03-4625-9c3c-6f55f0873aa8.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature12](https://user-images.githubusercontent.com/36091766/212429558-2ac641d1-bb15-45ed-bb4b-d932e9943373.png)


channel-13 | channel-14
--- | --- 
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature13](https://user-images.githubusercontent.com/36091766/212429571-f9ab281d-0a0d-469f-8ce0-07a69eda83ba.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature14](https://user-images.githubusercontent.com/36091766/212429572-5a8e7862-bd7b-457d-ae7b-5e28c5316e88.png)

channel-15|channel-16
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature15](https://user-images.githubusercontent.com/36091766/212429591-b494a8ca-74ca-4bf4-821d-871a494ed157.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature16](https://user-images.githubusercontent.com/36091766/212429593-3d963d18-b12a-40dc-a056-5f95426b8275.png)

channel-17| channel-18
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature17](https://user-images.githubusercontent.com/36091766/212429602-99e39aea-a74d-4f4a-94a1-3bcb6e5f611d.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature18](https://user-images.githubusercontent.com/36091766/212429603-0a82b648-b815-4ed9-ac4e-ebc7461b3aba.png)

|channel-19|channel-20
--- | --- |
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature19](https://user-images.githubusercontent.com/36091766/212429614-256d979e-0213-499c-9d10-61b696c1f105.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature20](https://user-images.githubusercontent.com/36091766/212429616-cfde73a0-5520-450e-94d8-09eee9bb7afb.png)

channel-21 | channel-22
--- |---
![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature21](https://user-images.githubusercontent.com/36091766/212429630-14893787-1eb2-4eef-b266-2107eeaa4d8c.png)|![gsi_hofx_vs_jedi_hofx_2021080100_atms_n20_brightness_temperature22](https://user-images.githubusercontent.com/36091766/212429632-4be88f27-bd3c-4dcc-a7c8-5c51d3fef98b.png)

**Comment by emilyhcliu** [comment]
### ATMS N20 Channel-7

**Compared to GSI, UFO has two more points (south pole, sea ice) filtered out by HydrometeorCheck. (cloud/rain/precipitation screening)**

GSI | UFO |
--- | ---
![gsi_atms_n20_channel7](https://user-images.githubusercontent.com/36091766/212438815-537a20e7-2a92-4d96-bb07-85b62b014318.png)|![ufo_atms_n20_channel7](https://user-images.githubusercontent.com/36091766/212438826-9e374a83-136b-4751-a268-92391948c0a3.png)

latitude |  longitude | ObsValue| Innovation|  GsiEffectiveQC|  EffectiveQC| EffectiveError  
--- | --- | --- | --- | --- | --- | ---
-73.179237|  277.554077|  207.757874|   -0.062546|   0 |12  |   -3.368795e+38 
-69.398537|  359.459717|  209.842499 |   0.037689 |  0  |   12 | -3.368795e+38 


### ATMS NPP Channel-7

**Compared to GSI, UFO has one more point (south pole, sea ice) filtered out by HydrometeorCheck. (cloud/rain/precipitation screening)**

GSI | UFO |
--- | ---
![gsi_atms_npp_channel7](https://user-images.githubusercontent.com/36091766/212440710-3c895650-8f6a-4cf5-86f9-966b917c335f.png)|![ufo_atms_npp_channel7](https://user-images.githubusercontent.com/36091766/212440714-2bce9348-6030-4b51-b4eb-7c5525082a5e.png)

latitude |  longitude | ObsValue| Innovation|  GsiEffectiveQC|  EffectiveQC| EffectiveError  
--- | --- | --- | --- | --- | --- | ---
-77.259377|  172.936035|  213.148590|   -0.248276|   0  |  12  | -3.368795e+38
