### ISSUE TITLE
AMSU-A Obs Validation

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/JEDI-T2O#44]
**This issue will be used to track progress on the development and validation of radiances in UFO for GDAS in four stages:**

**1. Validation with GeoVaLs from GSI:**
- [x] HofX 
   - [x] GSI NC diagnostic converter needs to update to output GSI HofX directly instead of output HofX based on O-(O-HofX).  This change is necessary to avoid producing [**Zero HofX** ](https://github.com/NOAA-EMC/JEDI-T2O/issues/44#issuecomment-1376759413)at locations where the observations are missing
   - [x] Regenerate GeoVaLs and Obs 
   - [x] Validation results: [**100% replication**](https://github.com/NOAA-EMC/JEDI-T2O/issues/44#issuecomment-1377495811) of GSI for all platforms.  New input files are available on ORION: 

```    
          Date: 2021080100
          Resolution: C768
          GeoDir=/work2/noaa/da/eliu/ufoeval/GSIobserver/2021080100/ioda/geovals/
          ObsDir=/work2/noaa/da/eliu/ufoeval/GSIobserver/2021080100/ioda/obs/
          BCDir=/work2/noaa/da/cmartin/UFO_eval/data/gsi_geovals_l127/nofgat_aug2021/20221027/bc/
          FixDir=/work2/noaa/da/cmartin/GDASApp/fix/
```
- [x] Update/improve QC filters (GSI QC steps in GSI setuprad.f90 and qcmod.f90 (qc_amsua subroutine)

![AMSU-A QC FlowChart](https://user-images.githubusercontent.com/36091766/188951199-0542ca77-8162-43ca-97fb-a768428ce5aa.png)
   - [x] The @ObsError is set to missing in the input obs file
   - [x] Code change is required for ObsErrorFactorSituDependMW to avoid getting the original obs error from the input obs file
   - [x] YAML update
           - Improve the use of generic filters and obs functions in the YAML
           - Add filters to output diagnostic variables in YAML
           - Remove the need to repeatedly re-compute the same obs functions used in various filters
- [x] QC count  and obs error checks using-GSI produced GeoVaLs
   - [x] Code change is required GSI NC diagnostic converter to output the correct `varinv` (output `varinv` instead of `varinv0`)
   - [x]  Validation Results: [**Obs Error**](https://github.com/NOAA-EMC/JEDI-T2O/issues/44#issuecomment-1377632919) and [**HofX**](https://github.com/NOAA-EMC/JEDI-T2O/issues/44#issuecomment-1381289049)
      - [x] amsua_n19 --- 100% replication of GSI
      - [x] amsua_n18 --- 100% replication of GSI
      - [x] amsua_n15 --- 100% replication of GSI
      - [x] amsua_metop-a --- 100% replication of GSI
      - [x] amsua_metop-b --- 100% replication of GSI
      - [x] amsua_metop-c --- 100 % replication of GSI
      - [x] amsua_aqua  --- data not available in the operational data stream

**2. UFO development:**
- [ ] Separate `HydrometeorCheckAMSUA` into three separate checks for clarity --- work in progress
       The `HydrometeorCheckAMSUA` will be separated into three single checks:  RainCheck, CloudCheck, and SurfaceEmissivityCheck, and these checks will be filtered over land and ocean separately.  
- [ ] Modify existing Gaussian thinning filter to reproduce GSI result   --- work in progress
- [ ] Check with JEDI team about keeping the thinned data in the obs space
- [ ] Add thinning filter and a few more QC steps (from GSI read_bufrtovs.f90 routine) in YAML
- [ ] Validation with GSI result

**3. IODA-converter development:**
- [x] Prepare AMSU-A YAML for bufr converter 
- [ ] Work with Cory to add the capability of converting AMSU-A bufr to IODA in GDASApp workflow

**4. HofX computation in FV3-JEDI with GDASApp workflow:**
- [ ] Test workflow (plumbing)
- [ ] Check statistics
- [ ] Summarize and explain differences between GSI and UFO

**Comment by ADCollard** [comment]
This also references #38

**Comment by emilyhcliu** [comment]
List of Platform-
- [ ] N-19
- [ ] N-18
- [ ] N-15
- [ ] MetOp-A
- [ ] MetOp-B
- [ ] Aqua

**Comment by ADCollard** [comment]
It was noted that there are observations where GSIHofX is zero.  See plot below.   This is only occuring where the observation value is set to missing, so appears to be a quirk in the GSI.  I am still trying to track down exactly where the logic is that is doing this, but this should not adversely affect JEDI validation.

<img width="698" alt="Screen Shot 2022-08-26 at 16 03 48 PM" src="https://user-images.githubusercontent.com/40322596/186982813-f34110bf-bf6a-4019-909f-a9ac455c0416.png">

**Comment by emilyhcliu** [comment]
**Here are a few more examples of zero HofX from GSI caused by missing observations:**
This is fixed by output GSI HofX instead of getting HofX from Obs-(Obs-HofX) 

**AMSU-A N19**
channel-12 | channel-13
--- | ---
![](https://user-images.githubusercontent.com/36091766/211469734-492986cf-1041-4ba8-b517-ca6e79213d35.png) | ![](https://user-images.githubusercontent.com/36091766/211469577-208b5b86-62a8-4f32-842d-e94d8445c755.png)


**AMSU-A MetOp-A**
channel-7 | channel-8
--- | ---
![](https://user-images.githubusercontent.com/36091766/211467994-fd2e1d60-1e06-4667-a419-d36edc420079.png) | ![](https://user-images.githubusercontent.com/36091766/211467996-986d6837-0e75-4fc2-b28d-a556fdeefe33.png)

**Comment by emilyhcliu** [comment]
### Example HofX (No QC) Validation: GSI vs. JEDI UFO

**AMSU-A MetOp-A**
Channel-1 | Channel-2 | Channel-3
--- | --- | ---
![](https://user-images.githubusercontent.com/36091766/211599744-175dc9bf-952f-476b-b44c-7e01ea9165ef.png) |![](https://user-images.githubusercontent.com/36091766/211599745-80e0cbb4-14c5-418f-8047-9f030b025522.png)|![](https://user-images.githubusercontent.com/36091766/211599746-8a74c693-86a4-42c6-984f-17dddbe3b030.png)

Channel-4 | Channel-5 | Channel-6
--- | --- | ---
![](https://user-images.githubusercontent.com/36091766/211600083-5bbd9029-1f63-460e-874a-fb88429d4489.png) |![](https://user-images.githubusercontent.com/36091766/211600086-2e80310f-cc7d-46cf-93ea-355738747ca7.png) |![](https://user-images.githubusercontent.com/36091766/211600088-4d1858c8-af02-45cb-97e6-643a413c89d9.png)

Channel-7 | Channel-8 | Channel-9
--- | ---| ---
![](https://user-images.githubusercontent.com/36091766/211600800-0fe06c4a-fe2c-42fa-90b7-418113ba7eee.png)|![](https://user-images.githubusercontent.com/36091766/211600801-7011cb30-db9b-4668-8f05-e67c26026876.png)|![](https://user-images.githubusercontent.com/36091766/211600802-7ce2a5ab-2f1e-4b52-a226-ab276ddd0722.png)
 

Channel-10 | Channel-11 | Channel-12
--- | --- | ---
![](https://user-images.githubusercontent.com/36091766/211600943-064acb13-565a-466e-85f0-dde8653fe07d.png)|![](https://user-images.githubusercontent.com/36091766/211600944-e9368774-7c60-41bd-bf89-0f3f0de18a9c.png)|![](https://user-images.githubusercontent.com/36091766/211600946-f523ef88-88c4-42ce-82f2-47c3b6b6136e.png)

Channel-13 | Channel-14 | Channel-15
--- | --- | ---
![](https://user-images.githubusercontent.com/36091766/211601309-0286fcb5-f925-4b48-b54a-75ec4644f6dd.png)|![](https://user-images.githubusercontent.com/36091766/211601314-57e77e8a-e3cd-4c67-a68a-7e9043ff7951.png)|![](https://user-images.githubusercontent.com/36091766/211601315-a38beca0-4b6e-4c75-b619-91260628ad91.png)

**Comment by emilyhcliu** [comment]
Found a bug in GSI for AMSU-A QC.  

Original code (with bug)

```
! If window channels are missing, skip the following QC and do not
! assimilate channels 1-6 & 15.

  if (any(abs(tbc((/ ich238, ich314, ich528, ich536, ich544, ich890 /))) &         !orig
       > 200.0_r_kind))  then

```

Code with bug fix

**Comment by emilyhcliu** [comment]
### Initial (Original) / Final Observation Error Comparison: GSI vs. JEDI UFO

**Result of QC filtering check  (using AMSU-A N19 as an example)**
The following figures show the GSI final observation error on the left and UFO on the right
The data count passed QC is listed above the color bar

**Original Observation Error**
**Channel-2**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211625908-ea2bc0dc-3c62-47fe-b34d-33161bfd4a4d.png)|![](https://user-images.githubusercontent.com/36091766/211625813-62ee9c4e-34ed-41fc-8cff-e5947c167cc5.png)

**Observation Error after a series of data filtering and error inflation processes:**
**Channel-2**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623283-b74509dc-c1e1-4f3f-a26f-b3332ce49c94.png)|![](https://user-images.githubusercontent.com/36091766/211623303-e1b96be0-36c6-4354-bb5f-7fc4aeca2772.png)

**Channel-1**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211622526-47d344f1-52c8-4dcf-aa96-2c23c7754204.png)|![](https://user-images.githubusercontent.com/36091766/211622479-fe6d6c83-ef1a-4be6-9e2f-54ee6e096ccd.png)

**Channel-3**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623338-069e308a-ea33-432f-b2cd-45638ef8df57.png)|![](https://user-images.githubusercontent.com/36091766/211623357-92c5cdcd-0b48-4df0-9c32-a4c68d744a77.png)

**Channel-4**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623386-221d2982-044c-46a2-b0cf-b6b440427574.png)|![](https://user-images.githubusercontent.com/36091766/211623400-a6203dc0-bfc8-441c-8ead-5f05ccb5a3c6.png)

**Channel-5**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623420-9457494f-c8a1-47b1-a2a2-948ee97c0916.png)|![](https://user-images.githubusercontent.com/36091766/211623432-3e38aa27-80a7-457b-9629-5e381b4fd75c.png)

**Channel-6**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623449-55ff4abe-53d7-4df1-a80d-d64209effb38.png)|![](https://user-images.githubusercontent.com/36091766/211623464-1bd6c3a4-78c1-49ad-933f-6331af68f183.png)

**Channel-7**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623490-e73fe3b3-81cd-4eea-997a-74faad8f5a09.png)|![](https://user-images.githubusercontent.com/36091766/211623500-6af30449-36a1-427e-ae90-68f704643f89.png)

**Channel-8**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623549-30abeb97-be38-4b56-9239-d60640b21fd1.png)|![](https://user-images.githubusercontent.com/36091766/211623513-dc54ae15-557e-4a17-842f-5f841b43bb22.png)

**Channel-9**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623591-6830394b-6554-4ad2-8b26-d5f99f809349.png)|![](https://user-images.githubusercontent.com/36091766/211623604-7d732ad4-c4bb-461b-99ff-03f44edbe55d.png)

**Channel-10**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623648-783c99a1-4818-4dde-bd51-66fa3af38d8c.png)|![](https://user-images.githubusercontent.com/36091766/211623680-1a752eff-2c1d-482d-b6b5-51fd3789b213.png)

**Channel-11**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623711-46b893f0-e5fa-4663-b628-a2ffcfbd8180.png)|![](https://user-images.githubusercontent.com/36091766/211623727-11ab910a-af23-42dc-921f-52a6291ee23e.png)

**Channel-12**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623759-93775df8-82e1-4dff-b452-4a1c5cf7f6fc.png)|![](https://user-images.githubusercontent.com/36091766/211623777-1be0081a-9e36-457a-ae52-d8cc82f82973.png)

**Channel-13**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623801-131fdd1e-b0e1-47f6-9ee8-daa56f2eea74.png)|![](https://user-images.githubusercontent.com/36091766/211623817-2c63701c-e7a6-48c1-8376-b1e29ae5c759.png)

**Channel-14**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623834-b2ea9258-50c0-44e9-b2c6-51132cb26075.png)|![](https://user-images.githubusercontent.com/36091766/211623899-5a50c138-7d26-43b3-ab10-84ff740a22a4.png)

**Channel-15**
GSI | UFO |
--- | ---
![](https://user-images.githubusercontent.com/36091766/211623930-cf027f48-1312-47d1-a2e8-01b44095cabc.png)|![](https://user-images.githubusercontent.com/36091766/211623946-a9db3a41-ff0f-4dc0-b064-2296bda9e726.png)

**Comment by emilyhcliu** [comment]
### **HofX  Comparison between GSI vs. JEDI UFO:  No QC (Black) and QC (Red)**
**AMSU-N19**
Channel 1 | Channel 2 |Channel 3
--- | --- |---
![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature1](https://user-images.githubusercontent.com/36091766/212233866-a32200e4-3b07-4193-bcfb-195bbb019927.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature2](https://user-images.githubusercontent.com/36091766/212233868-7d8bd3c7-3b51-4a39-90f7-a4f559c37e73.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature3](https://user-images.githubusercontent.com/36091766/212234055-bfb7ba2b-79d4-4b30-aeb3-b957f42f7e99.png)

Channel 4 | Channel 5 |Channel 6
--- | --- |---
![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature4](https://user-images.githubusercontent.com/36091766/212234214-7ca8a4ab-9af6-4909-b026-6050a7c6226e.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature5](https://user-images.githubusercontent.com/36091766/212234216-e131ccca-537f-456c-bf2b-17249f6db009.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature6](https://user-images.githubusercontent.com/36091766/212234218-003742dc-56de-49c2-84a1-56b5e8f6083b.png)

Channel 7 | Channel 8 |Channel 9
--- | --- |---
![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature7](https://user-images.githubusercontent.com/36091766/212234234-6572cc7f-26a5-4fdb-9a52-9c662ff253eb.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature8](https://user-images.githubusercontent.com/36091766/212234240-56dcfd7b-ff75-4051-b8b2-cf0138a38962.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature9](https://user-images.githubusercontent.com/36091766/212234242-8c350a01-a4f6-41d1-a433-5c8bd21d49f0.png)

Channel 10 | Channel 11 |Channel 12
--- | --- |---
![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature10](https://user-images.githubusercontent.com/36091766/212234248-56b1c9c8-c6fc-4dcd-b6af-ed9f60656481.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature11](https://user-images.githubusercontent.com/36091766/212234249-d829e8c1-7f59-445f-b07e-ee4fa5b7bd42.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature12](https://user-images.githubusercontent.com/36091766/212234251-be961078-e04f-4f70-ba3e-e92b39c2d28c.png)

Channel 13| Channel 14 |Channel 15
--- | --- |---
![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature13](https://user-images.githubusercontent.com/36091766/212234285-4239be98-f870-4276-b557-bd4fc9cc650c.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature14](https://user-images.githubusercontent.com/36091766/212234286-91496f3c-e961-4029-b63f-9c8eb3f37995.png)|![gsi_hofx_vs_jedi_hofx_2021080100_amsua_n19_brightness_temperature15](https://user-images.githubusercontent.com/36091766/212234288-96a420ff-5675-4645-98fc-deca724ef6a3.png)
